config/routes.rb
TodoApp::Application.routes.draw do

   resources :users do
    resources :lists do
      resources :tasks
    end
   end

   resources :sessions, only:[:create]
   match "/signin"=>"sessions#new", as: "signin"
   match "/signout"=>"sessions#destroy", as: "signout", via: :delete

  root to: 'pages#home'
  match "/lists/:list_id/tasks/:task_id/complete" => "tasks#complete", as: :complete_task

end

app/models/list.rb
class List < ActiveRecord::Base
  attr_accessible :description, :name
  validates :description,:name, presence: true
  has_many :tasks ,dependent: :destroy   # destroy associated tasks also
  belongs_to :user
end

app/models/task.rb
class Task < ActiveRecord::Base
  attr_accessible :completed, :description
  belongs_to :list
  validates :description, presence: true
  scope :completed, where(completed: true)
  scope :incomplete, where(completed: false )
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :nick_name, :password, :password_confirmation
  has_secure_password
  validates :password, presence: true
   before_save :create_remember_token
  has_many :lists

  def new

  end


  private
   def create_remember_token
     self.remember_token = SecureRandom.urlsafe_base64 # If u just say remember_token= ...   then local variable
                                                       # remember_token is created...If u want to access table column
                                                       #remember_token...u need to use self.remember_token...
   end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
  before_filter :set_no_cache
   private
  def set_no_cache
    response.headers["Cache-Control"] = "no-cache, no-store, max-age=0, must-revalidate"
    response.headers["Pragma"] = "no-cache"
    response.headers["Expires"] = "Fri, 01 Jan 1990 00:00:00 GMT"
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController


  before_filter :signed_in_user       # though correct_user also takes care of signed_in, we need this bcos of session[:return_to]= request.fullpath...its nice to have it
  before_filter  {|c| c.correct_user params[:user_id] }   # Use block form ....This is the way to send parameters to method used in before_filter
  before_filter  :find_list, only:[:show,:update,:destroy]

  def show
    @task = @list.tasks.build
  end

  def create
    @list= current_user.lists.build(params[:list])
     respond_to do |format|
       format.js
     end
  end

=begin  Haven't implemented edit action
  def edit
    @list = List.find(params[:id])
  end
=end

  def update
    if @list.update_attributes(params[:list])
      redirect_to @list, notice: "List updated successfully"
    else
      render 'edit'
    end
  end

  def destroy
    respond_to do |format|
      format.js
    end
  end

  private
  def find_list
   redirect_to root_path unless @list= current_user.lists.find_by_id(params[:id])
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
    if signed_in?
      @lists = current_user.lists.all  # if u put only @lists= current_user.lists ...then if it is empty I think it doesnt return nil
     @new_list = current_user.lists.new   #changed from build to new...why ?
    end
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    if signed_in?
    redirect_to root_path   # if already signed in , dontr show signin page...he is upto no good
    else
    render 'new',layout: 'signin_fail'
    end
  end
  def create
   user = User.find_by_email(params[:session][:email])
   if user && user.authenticate(params[:session][:password])
     sign_in user
     redirect_back_or
   else
     flash.now[:error]= "Invalid email/password"
     render 'new' ,layout: "signin_fail"
   end

  end

  def destroy
   sign_out
   redirect_to controller: :pages, action: :home
  end


end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  before_filter :signed_in_user
  before_filter {|c| c.correct_user params[:user_id] }
  before_filter :find_list, only: [:create,:complete,:destroy,:update]    # why not use for update and destroy also ? ...maybe its not strictly necessary bcos we have used correct_user method...but it comes i use when we delete a task which is present in on list from another list...rhink bout it


  def create
    @task = @list.tasks.build(params[:task])
    respond_to do |format|
      format.js
    end
  end

  def update
    @task=@list.tasks.find(params[:id])
    @task.update_attributes(params[:task])
    respond_to do |format|
      format.html { redirect_to [current_user,@list], notice: 'Task completed' }
      format.js
    end
  end

  def destroy
    @task = @list.tasks.destroy(params[:id])   # destroy method returns the destroyed object, but since we used @list.tasks.destroy ...it returns array which contains destroyed object
   @task = @task.first
    respond_to do |format|
      format.js
    end
  end

  private

  def find_list
    redirect_to root_path unless @list= current_user.lists.find_by_id(params[:list_id])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_filter(only:[:show]) { |c| c.correct_user params[:id] }


  def new
    if signed_in?
      redirect_to root_path   # if already signed in , dontr show signup page...he is upto no good
    else
      @user = User.new()
    end
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      sign_in @user
      redirect_to controller: "pages",action: "home"
    else
      render 'new'
    end
  end

  def show
  # the helper method correct_user sets @user variable
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper


  def signed_in?()
    !current_user.nil?
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    @current_user ||=User.find_by_remember_token(cookies[:remember_token])
  end

  def current_user?(user)
    current_user==user
  end

  def correct_user(user_id)
    @user = User.find(user_id)
    redirect_to root_path unless current_user?(@user)
  end

  end

  def sign_in(user)
    cookies.permanent[:remember_token]= user.remember_token
    self.current_user = user # Why do we need writer method current_user..cant we just assign it like @current_user=user inside sign_in method
  end

  def sign_out
    cookies.delete(:remember_token)
    current_user =nil
  end

  def redirect_back_or
    if !session[:return_to].nil?
     redirect_to(session[:return_to])
    else
      redirect_to controller: "pages",action: :home
    end
    session.delete(:return_to)
  end

  def signed_in_user
    unless signed_in?
     session[:return_to]= request.fullpath
     flash[:alert]="Please sign in"
     redirect_to signin_path
    end
  end

  def correct_user(id)
    if User.find(id)

  end

end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <a class="brand" href="#">Todoodle</a>
      <nav>

          <% if signed_in? %>
            <ul class="nav pull-right">
              <li><%= link_to "Home", root_path %></li>
                <li class="divider"></li>
                  <li>
                    <%= link_to "Sign out", signout_path, method: "delete" %>
                  </li>
                </ul>
              </li>
          <% else %>
              <%= form_for :session,url:sessions_path,html:{class:"navbar-form pull-right",id:'signin_form_header'} do |f| %>
                   <%= f.text_field :email, placeholder: "email"  %>&nbsp&nbsp&nbsp<%= f.password_field :password ,placeholder: "password"%><%= f.submit "Sign in"%>
              <% end %>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_header_blank.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "Todoodle", root_path, id: "logo" %>

    </div>
  </div>
</header>

app/views/layouts/_show_flash_messages.html.erb
<% flash.each do |key, value| %>
    <div class="alert alert-<%= key==:notice ?'success':'error' %>"> <a class="close" data-dismiss="alert" href="#">&times;</a><%= value %></div>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Todoodle - <%= yield :title%></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/header' %>
<div class="container">
  <%= render 'layouts/show_flash_messages' %>
  <div class="row">
    <div class="span2">Sidebar</div>
    <div class="span9">
<%= yield %>
    </div>
    </div>
   </div>
</body>
</html>

app/views/layouts/signin_fail.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TODO <%= yield :title%></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/header_blank' %>
<div class="container">
  <%= render 'layouts/show_flash_messages' %>
  <div class="row">
    <div class="span3">Sidebar</div>
    <div class="span9">
      <%= yield %>
    </div>
  </div>
</div>
</body>
</html>

app/views/lists/_form.html.erb
  <%= simple_form_for [current_user,new_list],class:'form-horizontal',remote: true do |f| %>
      <%= f.input :name %>
      <%= f.input :description %>
      <%= f.submit %>
<% end %>

app/views/lists/_index.html.erb
<h3 class='main_header'>My TODO Lists</h3>
<div class="lists" id="lists">
<ul class="lists">
<% @lists.each do |list| %>
<%= render list %>
<% end  %>
 <div id='lists_empty' class='centre hero-unit'>You have no lists ! Create a list now !</div>  <!--We show this if there are no lists and hide it if a list  is created-->
</ul>
</div>

app/views/lists/_list.html.erb
<div id="list_<%=list.id%>" ><li><%= link_to list.name, user_list_path(current_user.id,list.id),class:'item_names' %> <%= link_to "(remove)",user_list_path(current_user.id,list.id),method: :delete,remote: true %></li></div>

app/views/lists/_new.html.erb
<%= render 'lists/form',new_list:new_list%>

app/views/lists/create.js.erb
<% if @list.save %>
$('ul.lists').append('<%= j render @list %>');
<% @list = List.new(); %>
 $('#new_list').html('<%= j render("lists/form",new_list:@list) %>');
<% else %>
$('#new_list').html('<%= j render("lists/form",new_list:@list) %>');
<% end %>

app/views/lists/destroy.js.erb
<% if @list %>
 $('#list_'+'<%= @list.id %>').remove();
<% else %>
//Add an error msg ..saying coudnt delete it
<% end %>

app/views/lists/edit.html.erb
<%= content_for :title,"Edit list" %>
<%= render 'form' %>

app/views/lists/show.html.erb
<%= content_for :title, @list.name %>
<div class='parent_div'><h2 class='main_header'><%= @list.name %> </h2>
<div class='list_desc'>--<i><%= @list.description %></i></div>
</div>
<h4 class='sub_header'>Unfinished Tasks</h3>
<div class="tasks" id="incomplete_tasks">
  <div class='empty_message'><div class='center hero-unit' id='tasks_empty'>My little grasshopper..You have no tasks left to do !</div></div>
  <% @list.tasks.incomplete.each do |task| %>
      <%= render task, list: @list %>
      <!--Here, we are sending @list,task variables to the rendered partial,
      because it needs those values,this is a way of passing local variables--we don't need to send 'task' variable
      because we used render task , so it checks model(class) name of task variable and goes accordingly to tasks/_task partial and the partial is passed the task instance variable as 'task' itself...
      so we can directly use it ...no need to pass it-->
  <% end %>
</div>
<h4 class='sub_header'>Finished Tasks</h3>
<div class="tasks" id="completed_tasks">
  <% @list.tasks.completed.each do |task| %>
      <%= render task, list: @list %>
  <% end %>
</div>
      <%= render 'tasks/task_form' %>
      <p><%= link_to "All lists", controller: :pages, action: :home %></p>

app/views/pages/home.html.erb
<% if signed_in? %>
    <%= render 'shared/home_signed_in' %>
 <% else %>
<%= render 'shared/home_not_signed_in' %>
<%end %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any?  %>
    <div id="error_explanation">
      <div class="alert alert-error">
      The form contains <%= pluralize(object.errors.count,"error") %>
     </div>
       <ul><% object.errors.full_messages.each do |msg| %>
          <li> <%= msg %></li>
        <% end %>
        </ul>
        </div>
    <% end %>

app/views/shared/_home_not_signed_in.html.erb
<%= content_for(:title,'Welcome') %>
<div class="center hero-unit">
  <h1>Welcome to Todoodly</h1>
  <h2>
    This is the home page for
    my sample ToDo List App
  </h2>
<%= link_to "Sign up now !", new_user_path , class: "btn btn-large btn-primary" %>
</div>

app/views/shared/_home_signed_in.html.erb
<%= content_for(:title,'Home') %>
<div id='user_nick_name'>Hi <%= current_user.nick_name %> !!</div>
<%= render 'lists/index' %>
<%= render 'lists/new', new_list:@new_list %>

app/views/tasks/_task.html.erb
<%= form_for [current_user, list, task], remote: true do |f| %>
    <%= f.label 'completed_'+task.object_id.to_s, class: 'checkbox' do %>
        <%= f.check_box :completed ,id:'task_completed_'+task.object_id.to_s%>   <!--have overridden default id because label works only if there is a unique id in each page-->
      <%= task.description %>
    <% end %>
    <%= link_to "remove",user_list_task_path(current_user, list, task),method: :delete,remote: true %>
    <%= f.submit "Update" %>        <!--We hide this button in jquery-->
<% end %>

app/views/tasks/_task_form.html.erb
<%= simple_form_for([current_user,@list, @task],class:'form-horizontal',remote: true) do |f| %>
    <%= f.input :description %>
    <%= f.submit %>
<% end %>

app/views/tasks/create.js.erb
<% if @task.save %>
$('#incomplete_tasks').append("<%= j render @task,list:@list %>");  //Add task to end of unfinished tasks list
$('#edit_task_<%=@task.id%>').submitOnCheck();
<% @task = @list.tasks.new(); %>   // Do this to clear previous info of task description inside new  'task_form'..this is generally what we do when we render a new form...we create a new empty model object corresponding to the form
$('#new_task').html("<%=j render 'tasks/task_form' %>");
<%else%>
//replace existing 'task_form' with the new 'task_form' which auto..adds validation errors using simple form.
$('#new_task').html("<%=j render 'tasks/task_form' %>");
<% end %>

app/views/tasks/destroy.js.erb
$('#edit_task_<%= @task.id %>').remove();

app/views/tasks/update.js.erb
<% if @task.completed? %>
$('#edit_task_<%= @task.id %>').appendTo('#completed_tasks');
<% else %>
$('#edit_task_<%= @task.id %>').appendTo('#incomplete_tasks');
<% end %>

app/views/users/_fields.html.erb
<%= render 'shared/error_messages', object: f.object %>
<%= f.label :nick_name %>
<%= f.text_field :nick_name %>
<%= f.label :email %>
<%= f.text_field :email %>
<%= f.label :password %>
<%= f.password_field :password %>
<%= f.label :password_confirmation, "Confirm Password" %>
<%= f.password_field :password_confirmation %>
<br/>

app/views/users/new.html.erb
<%= provide(:title, 'Sign up') %>

<div class="row">

  <div class="span6 offset1">
    <h2>Sign up</h2>
    <%= form_for(@user) do |f| %>
        <%= render 'fields', f: f %>
        <%= f.submit "Sign up", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title,@user.nick_name) %>
<%= @user.nick_name %>